version: "3"

services:
  postgres:
    image: mdillon/postgis:10-alpine
    container_name: postgres_analyzer_test
    environment:
      - POSTGRES_USER=analyzer
      - POSTGRES_PASSWORD=analyzer
    ports:
      - "25432:5432"

  dbmate:
    build: ./db
    container_name: dbmate_analyzer_test
    environment:
      - DATABASE_URL=postgres://analyzer:analyzer@postgres:5432/analyzer?sslmode=disable
    volumes:
      - ./db/migrations:/home/migrations
    depends_on:
      - postgres

  analyzer:
    build:
      context: .
      dockerfile: test/Dockerfile
    image: "instaleap/analyzer"
    container_name: analyzer
    ports:
      - "5000:80"
    environment:
      - ENVIRONMENT=test
      - LOWER_CASE_ENV_VARS=false
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=analyzer
      - POSTGRES_USER=analyzer
      - POSTGRES_PASSWORD=analyzer
      - DISABLE_LOG=false

    depends_on:
      - dbmate
    command: ./test.sh
