MAX_N_ALLOWED = 50

INVALID_DNA_SAMPLE = "INVALID_DNA_SAMPLE"
UNPROCESSABLE_ENTITY = "UNPROCESSABLE_ENTITY"
DATABASE_LAYER_ERROR = "DATABASE_LAYER_ERROR"
ALGORITHM_LAYER_ERROR = "ALGORITHM_LAYER_ERROR"
