MAX_N_ALLOWED = 100

INVALID_DNA_SAMPLE = "INVALID_DNA_SAMPLE"
UNSUPPORTED_DATA_TYPE = "UNSUPPORTED_DATA_TYPE"
UNPROCESSABLE_ENTITY = "UNPROCESSABLE_ENTITY"
DATABASE_LAYER_ERROR = "DATABASE_LAYER_ERROR"
