version: 0.0
os: linux
files:
  - source: app.service
    destination: /usr/lib/systemd/system/
  - source: app.env
    destination: /app/
  - source: app
    destination: /app/
hooks:
  BeforeInstall:
    - location: before_install.sh
  AfterInstall:
    - location: after_install.sh
  ApplicationStart:
    - location: start_service.sh
  ApplicationStop:
    - location: stop_service.sh
  ValidateService:
    - location: check_service.sh
