name: Build, pack and ship

on:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
      #runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build project
        run: cargo build --release --locked

      - name: Make artifact directory and database credentials
        run: |
          mkdir -p ./artifacts/python_explorations
          touch codedeploy/app.env
          echo POSTGRES_HOST=${{ secrets.POSTGRES_HOST }} >> app.env
          echo POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} >> app.env
          echo POSTGRES_PORT=${{ secrets.POSTGRES_PORT }} >> app.env
          echo POSTGRES_USER=${{ secrets.POSTGRES_USER }} >> app.env
          echo ENVIRONMENT="DEV" >> app.env

      - name: Create Zip File
        uses: montudor/action-zip@v0.1.1
        with:
          args: zip -qq -r ./artifacts/python_explorations/app.zip . -i "codedeploy/*" app

      - name: S3 Sync
        uses: jakejarvis/s3-sync-action@v0.5.1
        env:
          SOURCE_DIR: ./artifacts
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
